# CREDENCIAIS SENSÍVEIS (NÃO COMPARTILHE ESSE ARQUIVO)
# LinkedIn credentials removed by user request
linkedin:
  email: ""
  password: ""


telegram:
  bot_token: "8381269693:AAGM03-hgx29mRDz6Qg_8EIPYQRT_9ujbbQ"
  chat_id: "1641025073"

openai:
  api_key: "REPLACE_ME_NEW_KEY"

brave:
  api_key: "BSAqMYVN94axDE9y31j5iNsYGvW0VU1"

