# CREDENCIAIS SENSÍVEIS (NÃO COMPARTILHE ESSE ARQUIVO)
linkedin:
  email: "leonardopssantos@gmail.com"
  password: "L20002002a"

telegram:
  bot_token: "8381269693:AAGM03-hgx29mRDz6Qg_8EIPYQRT_9ujbbQ"
  chat_id: "1641025073"

openai:
  api_key: "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"

brave:
  api_key: "BSAqMYVN94axDE9y31j5iNsYGvW0VU1"

